pipeline {
    agent any

    tools {
        maven 'Maven'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                dir('my-jenkins-app') {
                    sh 'mvn clean package'
                }
            }
        }
        stage('Test') {
            steps {
                dir('my-jenkins-app') {
                    sh 'mvn test'
                }
            }
        }
    }

    post {
        success {
            echo 'Build succeeded!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}