pipeline {
    agent any

    tools {
        maven 'Maven'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm: [
                    $class: 'GitSCM',
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[url: 'https://github.com/rmassey6/group-proj-jenkins-app']]
                ]
            }
        }

        stage('Build') {
            steps {
                dir('my-jenkins-app') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Test') {
            steps {
                dir('my-jenkins-app') {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    dir('my-jenkins-app') {
                        jacoco(
                            execPattern: 'target/jacoco.exec',
                            classPattern: 'target/classes',
                            sourcePattern: 'src/main/java',
                            exclusionPattern: 'src/test*'
                        )
                    }
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('my-jenkins-app') {
                    withSonarQubeEnv('SonarQube') {
                        sh '''
                            mvn sonar:sonar \
                            -Dsonar.projectKey=my-jenkins-app \
                            -Dsonar.projectName="My Jenkins App" \
                            -Dsonar.java.binaries=target/classes
                        '''
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Build succeeded!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}